# Generated by Django 4.2.6 on 2023-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.FloatField(max_length=10)),
            ],
        ),
    ]
