# Generated by Django 4.2.6 on 2023-10-30 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_produto',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
