# Generated by Django 4.2.6 on 2023-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_data_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AlterField(
            model_name='produto',
            name='lm',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
