# Generated by Django 4.2.6 on 2023-11-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacoes',
            field=models.IntegerField(default=1.0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='media_avaliacoes',
            field=models.FloatField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
