# Generated by Django 4.2.6 on 2023-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
