# Generated by Django 4.2.6 on 2023-11-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_avaliacoes_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=130),
        ),
    ]
