# Generated by Django 4.2.6 on 2023-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_link_alter_produto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
