# Generated by Django 4.2.6 on 2023-12-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='info_produto',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
